import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'Coursiator',
    'app.tagline': 'Premium Language Learning Platform',
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'hero.title': 'Master Languages with AI-Powered Learning',
    'hero.subtitle': 'Live instructors + 24/7 AI tutor. SAT, IELTS, Business English, Arabic.',
    'hero.cta': 'Start Free Assessment',
    'features.title': 'Why Choose Coursiator?',
    'features.aiTutor': 'AI Speaking Tutor',
    'features.aiTutorDesc': '24/7 personalized conversation practice with real-time grammar correction.',
    'features.liveClasses': 'Live Classes',
    'features.liveClassesDesc': 'Expert instructors teaching in small groups with interactive feedback.',
    'features.placement': 'Smart Placement Test',
    'features.placementDesc': 'AI-powered assessment that creates your personalized learning roadmap.',
    'features.progress': 'Progress Tracking',
    'features.progressDesc': 'Real-time score predictions and detailed performance analytics.',
    'courses.title': 'Our Courses',
    'courses.ielts': 'IELTS Mastery',
    'courses.sat': 'SAT Excellence',
    'courses.business': 'Business English',
    'courses.arabic': 'Arabic Fluency',
    'footer.copyright': '© 2025 Coursiator. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'login.welcome': 'Welcome Back',
    'login.error.fill': 'Please fill in all fields',
    'login.error.failed': 'Login failed',
    'profile.title': 'Student Profile',
    'profile.subtitle': 'Manage your account settings and learning preferences',
    'profile.tab.profile': 'Profile',
    'profile.tab.settings': 'Settings',
    'profile.tab.security': 'Security',
    'profile.save': 'Save Changes',
    'profile.edit': 'Edit Profile',
    'profile.pic.title': 'Profile Picture',
    'profile.pic.upload': 'Upload New Photo',
    'profile.pic.desc': 'JPG, PNG or GIF (max 5MB)',
    'profile.personal': 'Personal Information',
    'profile.name': 'Full Name',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.country': 'Country',
    'profile.level': 'Proficiency Level',
    'profile.goal': 'Learning Goal',
    'profile.certs': 'Certificates & Reports',
    'profile.certs.download': 'Download',
    'profile.password': 'Change Password',
    'profile.currentPass': 'Current Password',
    'profile.newPass': 'New Password',
    'profile.confirmPass': 'Confirm New Password',
    'profile.updatePass': 'Update Password',
    'profile.sessions': 'Active Sessions',
    'profile.danger': 'Danger Zone',
    'profile.delete': 'Delete Account',
    'profile.deleteDesc': 'Once you delete your account, there is no going back. Please be certain.',
    'profile.deleteBtn': 'Delete My Account',
    'level.beginner': 'Beginner',
    'level.preInter': 'Pre-Intermediate',
    'level.intermediate': 'Intermediate',
    'level.upperInter': 'Upper Intermediate',
    'level.advanced': 'Advanced',
    'goal.ielts': 'IELTS Exam Preparation',
    'goal.sat': 'SAT Preparation',
    'goal.business': 'Business Communication',
    'goal.general': 'General English',
    'goal.arabic': 'Arabic Learning',
    'settings.language': 'Language',
    'settings.languageDesc': 'Choose your preferred language',
    'teacher.dash.title': 'Teacher Dashboard',
    'teacher.dash.subtitle': 'Manage your courses, videos, and student assessments',
    'teacher.upload': 'Upload Video',
    'teacher.tab.overview': 'Overview & Videos',
    'teacher.tab.assessments': 'Assessments',
    'teacher.tab.qa': 'Student Q&A',
    'assessment.create': 'Create Assessment',
    'assessment.title': 'Assessment Title',
    'assessment.course': 'Course',
    'assessment.addQuestion': 'Add Question',
    'assessment.questionText': 'Question Text',
    'assessment.questionType': 'Question Type',
    'assessment.option': 'Option',
    'assessment.correctAnswer': 'Correct Answer',
    'assessment.save': 'Save Assessment',
    'assessment.list.title': 'Title',
    'assessment.list.questions': 'Questions',
    'assessment.list.actions': 'Actions',
    'teacher.stat.earnings': 'Total Earnings',
    'teacher.stat.month': 'This Month',
    'teacher.stat.payout': 'Pending Payout',
    'teacher.stat.students': 'Total Students',
    'teacher.stat.completion': 'Completion Rate',
    'teacher.videos.title': 'Your Videos',
    'teacher.upload.title': 'Upload New Video',
    'teacher.edit.title': 'Edit Video',
    'teacher.form.title': 'Video Title',
    'teacher.form.course': 'Course',
    'teacher.form.file': 'Video File',
    'teacher.form.watermark': 'Enable Watermarking',
    'teacher.form.antiRecord': 'Enable Anti-Recording Protection',
    'teacher.reports.title': 'Reports & Analytics',
    'teacher.reports.subtitle': 'Track student progress and financial performance',
    'teacher.reports.tab.student': 'Student Reports',
    'teacher.reports.tab.financial': 'Financial Reports',
    'teacher.table.name': 'Student Name',
    'teacher.table.course': 'Course',
    'teacher.table.completion': 'Completion',
    'teacher.table.score': 'Avg. Score',
    'teacher.table.videos': 'Videos',
    'teacher.table.status': 'Status',
    'home.hero.title': 'Master Any Language with AI',
    'home.hero.subtitle': 'Personalized learning paths, AI-powered tutors, and expert-led courses.',
    'home.hero.cta': 'Start Free Trial',
    'home.stats.students': 'Students',
    'home.stats.success': 'Success Rate',
    'home.stats.support': 'AI Support',
    'home.features.title': 'Why Choose Coursiator?',
    'home.features.aiTutor': 'AI Tutor',
    'home.features.aiTutorDesc': 'Practice conversation 24/7 with our advanced AI',
    'home.features.liveClasses': 'Live Classes',
    'home.features.liveClassesDesc': 'Join interactive sessions with expert instructors',
    'home.features.placement': 'Placement Test',
    'home.features.placementDesc': 'Smart assessment to find your perfect level',
    'home.features.progress': 'Track Progress',
    'home.features.progressDesc': 'Detailed analytics and performance insights',
    'courses.subtitle': 'Choose your learning path and start mastering languages today',
    'courses.toast.already': 'You are already enrolled in this course.',
    'courses.toast.enrolled': 'Successfully enrolled!',
    'courses.toast.cart': 'Course added to cart',
    'cta.title': 'Ready to Transform Your Language Skills?',
    'cta.subtitle': 'Join thousands of students already learning with Coursiator.',
    'login.subtitle': 'Sign in to your Coursiator account',
    'login.role': 'Login as:',
    'login.student': 'Student',
    'login.instructor': 'Instructor',
    'login.admin': 'Admin',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.demo': 'Demo Credentials:',
    'login.demo.desc': 'Click a role button above to auto-fill demo credentials',
    'login.submit': 'Sign In',
    'login.submitting': 'Signing in...',
    'login.noAccount': "Don't have an account?",
    'login.create': 'Create an account',
    'login.back': 'Back to Home',
    'login.placeholder.email': 'you@example.com',
    'login.placeholder.password': '••••••••',
    'checkout.title': 'Secure Checkout',
    'checkout.billing': 'Billing Information',
    'checkout.firstName': 'First Name',
    'checkout.lastName': 'Last Name',
    'checkout.email': 'Email Address',
    'checkout.phone': 'Phone Number',
    'checkout.address': 'Street Address',
    'checkout.city': 'City',
    'checkout.state': 'State',
    'checkout.zip': 'ZIP Code',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.card': 'Credit/Debit Card (Stripe)',
    'checkout.paypal': 'PayPal',
    'checkout.cardNumber': 'Card Number',
    'checkout.expiry': 'Expiry Date',
    'checkout.cvv': 'CVV',
    'checkout.pay': 'Pay',
    'checkout.processing': 'Processing...',
    'checkout.summary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.discount': 'Discount',
    'checkout.tax': 'Tax',
    'checkout.total': 'Total',
    'checkout.empty': 'Cart is Empty',
    'checkout.emptyDesc': 'Add courses before proceeding to checkout',
    'checkout.back': 'Back to Courses',
    'checkout.backToCart': 'Back to Cart',
    'checkout.success': 'Payment Successful!',
    'checkout.successDesc': 'Your courses are being activated.',
    'checkout.invoice': 'Invoice',
  },
  ar: {
    'app.title': 'كورسياتور',
    'app.tagline': 'منصة تعلم اللغات المتميزة',
    'nav.home': 'الرئيسية',
    'nav.courses': 'الدورات',
    'nav.about': 'حول',
    'nav.contact': 'اتصل',
    'nav.login': 'دخول',
    'nav.signup': 'اشتراك',
    'hero.title': 'أتقن اللغات مع التعلم المدعوم بالذكاء الاصطناعي',
    'hero.subtitle': 'مدرسون مباشرون + معلم ذكي 24/7. SAT و IELTS والإنجليزية للأعمال والعربية.',
    'hero.cta': 'ابدأ التقييم المجاني',
    'features.title': 'لماذا تختار كورسياتور؟',
    'features.aiTutor': 'معلم ذكي للتحدث',
    'features.aiTutorDesc': 'ممارسة محادثة شخصية 24/7 مع تصحيح القواعد في الوقت الفعلي.',
    'features.liveClasses': 'فصول مباشرة',
    'features.liveClassesDesc': 'مدرسون خبراء يدرسون في مجموعات صغيرة مع ملاحظات تفاعلية.',
    'features.placement': 'اختبار التقييم الذكي',
    'features.placementDesc': 'تقييم مدعوم بالذكاء الاصطناعي ينشئ خريطة طريق التعلم الشخصية.',
    'features.progress': 'تتبع التقدم',
    'features.progressDesc': 'تنبؤات النقاط في الوقت الفعلي وتحليلات الأداء التفصيلية.',
    'courses.title': 'دوراتنا',
    'courses.ielts': 'إتقان الآيلتس',
    'courses.sat': 'التميز في السات',
    'courses.business': 'الإنجليزية للأعمال',
    'courses.arabic': 'طلاقة العربية',
    'footer.copyright': '© 2025 كورسياتور. جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'login.welcome': 'مرحباً بعودتك',
    'login.error.fill': 'يرجى ملء جميع الحقول',
    'login.error.failed': 'فشل تسجيل الدخول',
    'profile.title': 'ملف الطالب',
    'profile.subtitle': 'إدارة إعدادات حسابك وتفضيلات التعلم',
    'profile.tab.profile': 'الملف الشخصي',
    'profile.tab.settings': 'الإعدادات',
    'profile.tab.security': 'الأمان',
    'profile.save': 'حفظ التغييرات',
    'profile.edit': 'تعديل الملف',
    'profile.pic.title': 'صورة الملف الشخصي',
    'profile.pic.upload': 'رفع صورة جديدة',
    'profile.pic.desc': 'JPG, PNG أو GIF (حد أقصى 5 ميجابايت)',
    'profile.personal': 'المعلومات الشخصية',
    'profile.name': 'الاسم الكامل',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'رقم الهاتف',
    'profile.country': 'الدولة',
    'profile.level': 'مستوى الإتقان',
    'profile.goal': 'هدف التعلم',
    'profile.certs': 'الشهادات والتقارير',
    'profile.certs.download': 'تحميل',
    'profile.password': 'تغيير كلمة المرور',
    'profile.currentPass': 'كلمة المرور الحالية',
    'profile.newPass': 'كلمة المرور الجديدة',
    'profile.confirmPass': 'تأكيد كلمة المرور',
    'profile.updatePass': 'تحديث كلمة المرور',
    'profile.sessions': 'الجلسات النشطة',
    'profile.danger': 'منطقة الخطر',
    'profile.delete': 'حذف الحساب',
    'profile.deleteDesc': 'بمجرد حذف حسابك، لا يمكن التراجع عن ذلك. يرجى التأكد.',
    'profile.deleteBtn': 'حذف حسابي',
    'level.beginner': 'مبتدئ',
    'level.preInter': 'ما قبل المتوسط',
    'level.intermediate': 'متوسط',
    'level.upperInter': 'فوق المتوسط',
    'level.advanced': 'متقدم',
    'goal.ielts': 'تحضير امتحان IELTS',
    'goal.sat': 'تحضير SAT',
    'goal.business': 'التواصل التجاري',
    'goal.general': 'الإنجليزية العامة',
    'goal.arabic': 'تعلم العربية',
    'settings.language': 'اللغة',
    'settings.languageDesc': 'اختر لغتك المفضلة',
    'teacher.dash.title': 'لوحة تحكم المعلم',
    'teacher.dash.subtitle': 'إدارة دوراتك ومقاطع الفيديو وتقييمات الطلاب',
    'teacher.upload': 'رفع فيديو',
    'teacher.tab.overview': 'نظرة عامة ومقاطع الفيديو',
    'teacher.tab.assessments': 'التقييمات',
    'teacher.tab.qa': 'أسئلة الطلاب',
    'assessment.create': 'إنشاء تقييم',
    'assessment.title': 'عنوان التقييم',
    'assessment.course': 'الدورة',
    'assessment.addQuestion': 'إضافة سؤال',
    'assessment.questionText': 'نص السؤال',
    'assessment.questionType': 'نوع السؤال',
    'assessment.option': 'خيار',
    'assessment.correctAnswer': 'الإجابة الصحيحة',
    'assessment.save': 'حفظ التقييم',
    'assessment.list.title': 'العنوان',
    'assessment.list.questions': 'الأسئلة',
    'assessment.list.actions': 'إجراءات',
    'teacher.stat.earnings': 'إجمالي الأرباح',
    'teacher.stat.month': 'هذا الشهر',
    'teacher.stat.payout': 'دفعات معلقة',
    'teacher.stat.students': 'إجمالي الطلاب',
    'teacher.stat.completion': 'معدل الإكمال',
    'teacher.videos.title': 'مقاطع الفيديو الخاصة بك',
    'teacher.upload.title': 'رفع فيديو جديد',
    'teacher.edit.title': 'تعديل الفيديو',
    'teacher.form.title': 'عنوان الفيديو',
    'teacher.form.course': 'الدورة',
    'teacher.form.file': 'ملف الفيديو',
    'teacher.form.watermark': 'تفعيل العلامة المائية',
    'teacher.form.antiRecord': 'تفعيل حماية التسجيل',
    'teacher.reports.title': 'التقارير والتحليلات',
    'teacher.reports.subtitle': 'تتبع تقدم الطالب والأداء المالي',
    'teacher.reports.tab.student': 'تقارير الطلاب',
    'teacher.reports.tab.financial': 'التقارير المالية',
    'teacher.table.name': 'اسم الطالب',
    'teacher.table.course': 'الدورة',
    'teacher.table.completion': 'الإكمال',
    'teacher.table.score': 'متوسط الدرجات',
    'teacher.table.videos': 'الفيديوهات',
    'teacher.table.status': 'الحالة',
    'home.hero.title': 'أتقن أي لغة باستخدام الذكاء الاصطناعي',
    'home.hero.subtitle': 'مسارات تعليمية مخصصة، معلمين بالذكاء الاصطناعي، ودورات بقيادة خبراء.',
    'home.hero.cta': 'ابدأ التجربة المجانية',
    'home.stats.students': 'طلاب',
    'home.stats.success': 'نسبة النجاح',
    'home.stats.support': 'دعم الذكاء الاصطناعي',
    'home.features.title': 'لماذا تختار كورسياتور؟',
    'home.features.aiTutor': 'المعلم الذكي',
    'home.features.aiTutorDesc': 'مارس المحادثة على مدار 24 ساعة مع الذكاء الاصطناعي المتقدم',
    'home.features.liveClasses': 'فصول مباشرة',
    'home.features.liveClassesDesc': 'انضم إلى جلسات تفاعلية مع مدربين خبراء',
    'home.features.placement': 'اختبار تحديد المستوى',
    'home.features.placementDesc': 'تقييم ذكي لمعرفة مستواك المثالي',
    'home.features.progress': 'تتبع التقدم',
    'home.features.progressDesc': 'تحليلات مفصلة ورؤى للأداء',
    'courses.subtitle': 'اختر مسارك التعليمي وابدأ في إتقان اللغات اليوم',
    'courses.toast.already': 'أنت مسجل بالفعل في هذه الدورة.',
    'courses.toast.enrolled': 'تم التسجيل بنجاح!',
    'courses.toast.cart': 'تمت إضافة الدورة إلى سلة التسوق',
    'cta.title': 'مستعد لتحويل مهاراتك اللغوية؟',
    'cta.subtitle': 'انضم إلى آلاف الطلاب الذين يتعلمون بالفعل مع كورسياتور.',
    'login.subtitle': 'سجل الدخول إلى حسابك في كورسياتور',
    'login.role': 'تسجيل الدخول كـ:',
    'login.student': 'طالب',
    'login.instructor': 'معلم',
    'login.admin': 'مسؤول',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.demo': 'بيانات تجريبية:',
    'login.demo.desc': 'انقر فوق زر الدور أعلاه لملء البيانات التجريبية تلقائياً',
    'login.submit': 'تسجيل الدخول',
    'login.submitting': 'جاري تسجيل الدخول...',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.create': 'إنشاء حساب',
    'login.back': 'العودة للرئيسية',
    'login.placeholder.email': 'you@example.com',
    'login.placeholder.password': '••••••••',
    'checkout.title': 'دفع آمن',
    'checkout.billing': 'بيانات الفوترة',
    'checkout.firstName': 'الاسم الأول',
    'checkout.lastName': 'الاسم الأخير',
    'checkout.email': 'البريد الإلكتروني',
    'checkout.phone': 'رقم الهاتف',
    'checkout.address': 'العنوان',
    'checkout.city': 'المدينة',
    'checkout.state': 'المنطقة/المحافظة',
    'checkout.zip': 'الرمز البريدي',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.card': 'بطاقة ائتمان (Stripe)',
    'checkout.paypal': 'باي بال (PayPal)',
    'checkout.cardNumber': 'رقم البطاقة',
    'checkout.expiry': 'تاريخ الانتهاء',
    'checkout.cvv': 'رمز الأمان',
    'checkout.pay': 'دفع',
    'checkout.processing': 'جاري المعالجة...',
    'checkout.summary': 'ملخص الطلب',
    'checkout.subtotal': 'المجموع الفرعي',
    'checkout.discount': 'خصم',
    'checkout.tax': 'ضريبة',
    'checkout.total': 'الإجمالي',
    'checkout.empty': 'السلة فارغة',
    'checkout.emptyDesc': 'أضف دورات قبل المتابعة للدفع',
    'checkout.back': 'العودة للدورات',
    'checkout.backToCart': 'العودة للسلة',
    'checkout.success': 'تم الدفع بنجاح!',
    'checkout.successDesc': 'جاري تفعيل دوراتك الآن.',
    'checkout.invoice': 'رقم الفاتورة',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
